### PR TITLE
Ite ec

### PR DESCRIPTION
**Pull request by mkopec**

### CODE REVIEW

**Comment by miczyg1** [comment]
This is not the newest patchset

**Comment by mkopec** [comment]
@miczyg1 Yes, the newest patchest doesn't work on hardware, it irritates the EC and I had to pull the battery to shut off the laptop. This is the patchest used in https://github.com/3mdeb/flashrom/tree/tuxedo-v1.2

**Comment by miczyg1** [comment]
@mkopec at which point the EC is irritated?

**Comment by mkopec** [comment]
> @mkopec at which point the EC is irritated?

While running `flashrom -p ite_ecfw`, right after it prints the current FW version, it starts spamming the Enter key and stops responding. Touchpad also stops working.

**Comment by macpijan** [comment]
I change the base  from `dasharo-release` to `dasharo-develop` and merging this one, since this is the known-to-work patchset. I'm happy to overwrite the `dasharo-develop` branch, once we have a better functional patches.

**Comment by mkopec** [comment]
@miczyg1 Update: Looks like the issue only occurs if the AC adapter is not plugged while trying to run flashrom. It seems to be fine if the adapter is plugged in. Maybe it's an issue with the AC adapter detection in flashrom?

**Comment by mkopec** [comment]
Problem is fixed in the latest patchset: https://review.coreboot.org/c/flashrom/+/55715/29..30/ite_ecfw.c#875

**Comment by miczyg1** [comment]
@mkopec let's apply it on the develop branch if not done so yet

**Pull request merged**
